### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support 

### ISSUE THREAD

**Issue by Chess321** [expo-dev/expositor#3]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by expo-dev** [comment]
_This issue appears to have been opened, verbatim, in over 70 repositories, regardless of existing support for Armv9 or Neon._

Currently, Expositor officially supports only Linux, macOS, and Windows on AMD&thinsp;64 and Intel&thinsp;64.
